### ISSUE TITLE
wrong link for hawkeye

### ISSUE THREAD

**Issue by rhwarrier** [Sunbird-Obsrv/Community#8]
### Discussed in https://github.com/Sunbird-Obsrv/Community/discussions/6

<div type='discussions-op-text'>

<sup>Originally posted by **pramodkvarma** April  8, 2022</sup>
@rhwarrier page https://obsrv.sunbird.org/learn/product-and-developer-guide/report-configurator points to hawkeye PDF with DIKSHA logo etc. You need to move that to a proper Obsrv doc. Please track and fix. </div>

**Comment by rhwarrier** [comment]
The document has been updated with a generalised SB doc. Thanks.

**Comment by pramodkvarma** [comment]
That's great! 👍

Btw while doing that we should move those PDFs as markdowns (native docs pages). Navigation and then links from within the PDF etc takes me out of context a bit. See if you can move those into native docs. Shouldn't take too long I suppose.
