### ISSUE TITLE
Wrong data product link

### ISSUE THREAD

**Issue by rhwarrier** [Sunbird-Obsrv/Community#9]
### Discussed in https://github.com/Sunbird-Obsrv/Community/discussions/5

<div type='discussions-op-text'>

<sup>Originally posted by **pramodkvarma** April  8, 2022</sup>
@rhwarrier https://obsrv.sunbird.org/learn/product-and-developer-guide/data-service page has a PDF link to DIKSHA data exhaust doc! Please fix. </div>

**Comment by rhwarrier** [comment]
Updated with an SB doc. Thanks

**Comment by pramodkvarma** [comment]
Thanks for quick cleanup. But that page has API links to sunbird.org API docs (old common API pages) and also to this PDF which again lists the APIs. Please harmonize. Thanks once again for tracking these!
